[alias]
clar2wasm-install = "install --path . --locked --force"
fmt-stacks = "fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module"

# Uncomment the patch below to use a local version of the stacks-core modules
[patch.'https://github.com/stacks-network/stacks-core.git']
clarity = { path = "/home/acaccia/Builds/stacks-core/clarity" }
stacks-common = { path = "/home/acaccia/Builds/stacks-core/stacks-common" }
