set dotenv-load

run *args:
    RUST_BACKTRACE=full cargo run --release -- {{args}}

fmt:
    cargo fmt -- --config group_imports=StdExternalCrate,imports_granularity=Module

check:
    cargo clippy --manifest-path=./Cargo.toml --no-deps --all-features --all-targets -- -D warnings